version: "3.7"


services:
    nginx:
        image: dedevsey/psa_project_nginx
        container_name:  nginx
        restart: always
        ports:
            - "80:80"
    frontend:
        image: dedevsey/psa_project_frontend
        container_name:  frontend
        restart: always
        #  8000 for vue ui, 5000 for our vue app
        ports:
            - "8000:8000"
            - "5000:5000"
    backend:
        image: dedevsey/psa_project_backend
        container_name:  backend
        restart: always
        environment:
            - APP_NAME=FlaskApp
        expose:
            - 8080
