version: "3.7"


services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        environment:
            - APP_NAME=FlaskApp
        volumes:
            - './backend:/backend'
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name:  nginx
        restart: always
        volumes:
            - './nginx:/nginx'
        ports:
            - "80:80"
    frontend:
        build: ./frontend
        container_name:  frontend
        restart: always
        volumes:
            - './frontend:/frontend'

        #  8000 for vue ui, 5000 for our vue app
        ports:
            - "8000:8000"
            - "5000:5000"